// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MosogepBackend.Data;

#nullable disable

namespace MosogepBackend.Migrations
{
    [DbContext(typeof(Datadb))]
    partial class DatadbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("MosogepBackend.Gyarto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Nepszeru")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nev")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Gyartok");
                });

            modelBuilder.Entity("MosogepBackend.Models.Hiba", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasJsonPropertyName("id");

                    b.Property<DateTime>("HibaDatuma")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("hibadatum");

                    b.Property<int>("HibaKtsg")
                        .HasColumnType("INTEGER")
                        .HasJsonPropertyName("hibaktsg");

                    b.Property<int>("Hibakod")
                        .HasColumnType("INTEGER")
                        .HasJsonPropertyName("hibakod");

                    b.Property<int>("KulsoId")
                        .HasColumnType("INTEGER")
                        .HasJsonPropertyName("kulsoId");

                    b.Property<int>("MosogepId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MosogepId");

                    b.ToTable("Hiba");
                });

            modelBuilder.Entity("MosogepBackend.Models.Javitas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("HibaId")
                        .HasColumnType("INTEGER")
                        .HasJsonPropertyName("hibaid");

                    b.Property<int>("JavaJavitasId")
                        .HasColumnType("INTEGER")
                        .HasJsonPropertyName("id");

                    b.Property<int>("JavitasKtsg")
                        .HasColumnType("INTEGER")
                        .HasJsonPropertyName("javitasktsg");

                    b.Property<DateTime>("JavtiasDatum")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("javitasdatum");

                    b.Property<int>("Munkaber")
                        .HasColumnType("INTEGER")
                        .HasJsonPropertyName("munkaber");

                    b.Property<int>("Nyereseg")
                        .HasColumnType("INTEGER")
                        .HasJsonPropertyName("nyereseg");

                    b.Property<string>("Szerelo")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("szerelo");

                    b.HasKey("Id");

                    b.HasIndex("HibaId")
                        .IsUnique();

                    b.ToTable("Javitas");
                });

            modelBuilder.Entity("MosogepBackend.Models.JavitasNaplo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FeliratkozasDatuma")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gepadatai")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Hibakod")
                        .HasColumnType("INTEGER");

                    b.Property<int>("JatitasKtsg")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Szerelo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Naplo");
                });

            modelBuilder.Entity("MosogepBackend.Models.Mosogep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Azonosito")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("TEXT");

                    b.Property<int>("GepAraEuro")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GepAraFt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GyartoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HibaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxFordulat")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxToltotomeg")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tipus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GyartoId");

                    b.HasIndex("UserId");

                    b.ToTable("Gepek");
                });

            modelBuilder.Entity("MosogepBackend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("MosogepBackend.Models.Hiba", b =>
                {
                    b.HasOne("MosogepBackend.Models.Mosogep", null)
                        .WithMany("Hibak")
                        .HasForeignKey("MosogepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MosogepBackend.Models.Javitas", b =>
                {
                    b.HasOne("MosogepBackend.Models.Hiba", "Hiba")
                        .WithOne("Javitas")
                        .HasForeignKey("MosogepBackend.Models.Javitas", "HibaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hiba");
                });

            modelBuilder.Entity("MosogepBackend.Models.Mosogep", b =>
                {
                    b.HasOne("MosogepBackend.Gyarto", "Gyarto")
                        .WithMany("Gepek")
                        .HasForeignKey("GyartoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MosogepBackend.Models.User", "_User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gyarto");

                    b.Navigation("_User");
                });

            modelBuilder.Entity("MosogepBackend.Gyarto", b =>
                {
                    b.Navigation("Gepek");
                });

            modelBuilder.Entity("MosogepBackend.Models.Hiba", b =>
                {
                    b.Navigation("Javitas")
                        .IsRequired();
                });

            modelBuilder.Entity("MosogepBackend.Models.Mosogep", b =>
                {
                    b.Navigation("Hibak");
                });
#pragma warning restore 612, 618
        }
    }
}
